import type { PoolClient } from 'pg';
import db from '../config/db';
import type {
  Feedback,
  FeedbackRow,
  CreateFeedbackInput,
  UpdateFeedbackStatusInput,
} from '../models/feedback';
import { rowToFeedback } from '../models/feedback';

// ─── FeedbackRepository ───────────────────────────────────────────────────────

/**
 * Data-access layer for the `feedback` table.
 *
 * Rules:
 * - No business logic lives here — only SQL + row mapping.
 * - All queries use parameterised $n placeholders.
 * - Every method accepts an optional PoolClient for transaction support.
 */
export const FeedbackRepository = {
  // ── create ─────────────────────────────────────────────────────────────────

  /**
   * Inserts a new feedback record and returns the full persisted row.
   * UUID and timestamps are generated by the database.
   */
  async create(
    input: CreateFeedbackInput,
    client?: PoolClient,
  ): Promise<Feedback> {
    const query = `
      INSERT INTO feedback (message)
      VALUES ($1)
      RETURNING id, message, status, created_at
    `;
    const conn   = client ?? db;
    const result = await conn.query<FeedbackRow>(query, [input.message]);
    return rowToFeedback(result.rows[0] as FeedbackRow);
  },

  // ── findAll ────────────────────────────────────────────────────────────────

  /**
   * Returns every feedback record ordered by creation date (newest first).
   * Optionally filtered to a single status value.
   */
  async findAll(
    statusFilter?: string,
    client?: PoolClient,
  ): Promise<Feedback[]> {
    const conn = client ?? db;

    if (statusFilter) {
      const query = `
        SELECT id, message, status, created_at
        FROM   feedback
        WHERE  status = $1
        ORDER  BY created_at DESC
      `;
      const result = await conn.query<FeedbackRow>(query, [statusFilter]);
      return result.rows.map(rowToFeedback);
    }

    const query = `
      SELECT id, message, status, created_at
      FROM   feedback
      ORDER  BY created_at DESC
    `;
    const result = await conn.query<FeedbackRow>(query);
    return result.rows.map(rowToFeedback);
  },

  // ── findById ───────────────────────────────────────────────────────────────

  /**
   * Returns a single feedback record by UUID, or null if not found.
   */
  async findById(
    id: string,
    client?: PoolClient,
  ): Promise<Feedback | null> {
    const query = `
      SELECT id, message, status, created_at
      FROM   feedback
      WHERE  id = $1
      LIMIT  1
    `;
    const conn   = client ?? db;
    const result = await conn.query<FeedbackRow>(query, [id]);
    return result.rows.length > 0 ? rowToFeedback(result.rows[0] as FeedbackRow) : null;
  },

  // ── updateStatus ───────────────────────────────────────────────────────────

  /**
   * Updates the status of a feedback record.
   * Returns the updated record or null if the id was not found.
   */
  async updateStatus(
    input: UpdateFeedbackStatusInput,
    client?: PoolClient,
  ): Promise<Feedback | null> {
    const query = `
      UPDATE feedback
      SET    status = $1
      WHERE  id     = $2
      RETURNING id, message, status, created_at
    `;
    const conn   = client ?? db;
    const result = await conn.query<FeedbackRow>(query, [input.status, input.id]);
    return result.rows.length > 0 ? rowToFeedback(result.rows[0] as FeedbackRow) : null;
  },
};
